//
//  CountryRef.swift
//  OpenJetRecruitApp
//
//  Created by Yoann Cribier on 18/12/15.
//  Copyright © 2015 Yoann Cribier. All rights reserved.
//

import Foundation

class CountryRef {
    let table: [String: [String]] = [
        "AD": [ "AD" , "AND" , "20"  , "EU" , "Andorre"                                   , "Andorra"                                      ],
        "AE": [ "AE" , "ARE" , "784" , "AS" , "Émirats Arabes Unis"                       , "United Arab Emirates"                         ],
        "AF": [ "AF" , "AFG" , "4"   , "AS" , "Afghanistan"                               , "Afghanistan"                                  ],
        "AG": [ "AG" , "ATG" , "28"  , "NA" , "Antigua-et-Barbuda"                        , "Antigua and Barbuda"                          ],
        "AI": [ "AI" , "AIA" , "660" , "NA" , "Anguilla"                                  , "Anguilla"                                     ],
        "AL": [ "AL" , "ALB" , "8"   , "EU" , "Albanie"                                   , "Albania"                                      ],
        "AM": [ "AM" , "ARM" , "51"  , "AS" , "Arménie"                                   , "Armenia"                                      ],
        "AN": [ "AN" , "ANT" , "530" , "NA" , "Antilles Néerlandaises"                    , "Netherlands Antilles"                         ],
        "AO": [ "AO" , "AGO" , "24"  , "AF" , "Angola"                                    , "Angola"                                       ],
        "AQ": [ "AQ" , "ATA" , "10"  , "AN" , "Antarctique"                               , "Antarctica"                                   ],
        "AR": [ "AR" , "ARG" , "32"  , "SA" , "Argentine"                                 , "Argentina"                                    ],
        "AS": [ "AS" , "ASM" , "16"  , "OC" , "Samoa Américaines"                         , "American Samoa"                               ],
        "AT": [ "AT" , "AUT" , "40"  , "EU" , "Autriche"                                  , "Austria"                                      ],
        "AU": [ "AU" , "AUS" , "36"  , "OC" , "Australie"                                 , "Australia"                                    ],
        "AW": [ "AW" , "ABW" , "533" , "NA" , "Aruba"                                     , "Aruba"                                        ],
        "AX": [ "AX" , "ALA" , "248" , "EU" , "Îles Åland"                                , "Åland Islands"                                ],
        "AZ": [ "AZ" , "AZE" , "31"  , "AS" , "Azerbaïdjan"                               , "Azerbaijan"                                   ],
        "BA": [ "BA" , "BIH" , "70"  , "EU" , "Bosnie-Herzégovine"                        , "Bosnia and Herzegovina"                       ],
        "BB": [ "BB" , "BRB" , "52"  , "NA" , "Barbade"                                   , "Barbados"                                     ],
        "BD": [ "BD" , "BGD" , "50"  , "AS" , "Bangladesh"                                , "Bangladesh"                                   ],
        "BE": [ "BE" , "BEL" , "56"  , "EU" , "Belgique"                                  , "Belgium"                                      ],
        "BF": [ "BF" , "BFA" , "854" , "AF" , "Burkina Faso"                              , "Burkina Faso"                                 ],
        "BG": [ "BG" , "BGR" , "100" , "EU" , "Bulgarie"                                  , "Bulgaria"                                     ],
        "BH": [ "BH" , "BHR" , "48"  , "AS" , "Bahreïn"                                   , "Bahrain"                                      ],
        "BI": [ "BI" , "BDI" , "108" , "AF" , "Burundi"                                   , "Burundi"                                      ],
        "BJ": [ "BJ" , "BEN" , "204" , "AF" , "Bénin"                                     , "Benin"                                        ],
        "BL": [ "BL" , "BLM" , "652" , "NA" , "Saint Barthelemy"                          , "Saint Barthelemy"                             ],
        "BM": [ "BM" , "BMU" , "60"  , "NA" , "Bermudes"                                  , "Bermuda"                                      ],
        "BN": [ "BN" , "BRN" , "96"  , "AS" , "Brunéi Darussalam"                         , "Brunei Darussalam"                            ],
        "BO": [ "BO" , "BOL" , "68"  , "SA" , "Bolivie"                                   , "Bolivia"                                      ],
        "BQ": [ "BQ" , "BES" , "535" , "NA" , "Bonaire, Sint Eustatius and Saba"          , "Bonaire, Sint Eustatius and Saba"             ],
        "BR": [ "BR" , "BRA" , "76"  , "SA" , "Brésil"                                    , "Brazil"                                       ],
        "BS": [ "BS" , "BHS" , "44"  , "NA" , "Bahamas"                                   , "Bahamas"                                      ],
        "BT": [ "BT" , "BTN" , "64"  , "AS" , "Bhoutan"                                   , "Bhutan"                                       ],
        "BV": [ "BV" , "BVT" , "74"  , "AN" , "Île Bouvet"                                , "Bouvet Island"                                ],
        "BW": [ "BW" , "BWA" , "72"  , "AF" , "Botswana"                                  , "Botswana"                                     ],
        "BY": [ "BY" , "BLR" , "112" , "EU" , "Bélarus"                                   , "Belarus"                                      ],
        "BZ": [ "BZ" , "BLZ" , "84"  , "NA" , "Belize"                                    , "Belize"                                       ],
        "CA": [ "CA" , "CAN" , "124" , "NA" , "Canada"                                    , "Canada"                                       ],
        "CC": [ "CC" , "CCK" , "166" , "AS" , "Îles Cocos (Keeling)"                      , "Cocos (Keeling) Islands"                      ],
        "CD": [ "CD" , "COD" , "180" , "AF" , "République Démocratique du Congo"          , "The Democratic Republic Of The Congo"         ],
        "CF": [ "CF" , "CAF" , "140" , "AF" , "République Centrafricaine"                 , "Central African"                              ],
        "CG": [ "CG" , "COG" , "178" , "AF" , "République du Congo"                       , "Republic of the Congo"                        ],
        "CH": [ "CH" , "CHE" , "756" , "EU" , "Suisse"                                    , "Switzerland"                                  ],
        "CI": [ "CI" , "CIV" , "384" , "AF" , "Côte d'Ivoire"                             , "Côte d'Ivoire"                                ],
        "CK": [ "CK" , "COK" , "184" , "OC" , "Îles Cook"                                 , "Cook Islands"                                 ],
        "CL": [ "CL" , "CHL" , "152" , "SA" , "Chili"                                     , "Chile"                                        ],
        "CM": [ "CM" , "CMR" , "120" , "AF" , "Cameroun"                                  , "Cameroon"                                     ],
        "CN": [ "CN" , "CHN" , "156" , "AS" , "Chine"                                     , "China"                                        ],
        "CO": [ "CO" , "COL" , "170" , "SA" , "Colombie"                                  , "Colombia"                                     ],
        "CR": [ "CR" , "CRI" , "188" , "NA" , "Costa Rica"                                , "Costa Rica"                                   ],
        "CU": [ "CU" , "CUB" , "192" , "NA" , "Cuba"                                      , "Cuba"                                         ],
        "CV": [ "CV" , "CPV" , "132" , "AF" , "Cap-vert"                                  , "Cape Verde"                                   ],
        "CX": [ "CX" , "CXR" , "162" , "AS" , "Île Christmas"                             , "Christmas Island"                             ],
        "CY": [ "CY" , "CYP" , "196" , "EU" , "Chypre"                                    , "Cyprus"                                       ],
        "CZ": [ "CZ" , "CZE" , "203" , "EU" , "République Tchèque"                        , "Czech Republic"                               ],
        "DE": [ "DE" , "DEU" , "276" , "EU" , "Allemagne"                                 , "Germany"                                      ],
        "DJ": [ "DJ" , "DJI" , "262" , "AF" , "Djibouti"                                  , "Djibouti"                                     ],
        "DK": [ "DK" , "DNK" , "208" , "EU" , "Danemark"                                  , "Denmark"                                      ],
        "DM": [ "DM" , "DMA" , "212" , "NA" , "Dominique"                                 , "Dominica"                                     ],
        "DO": [ "DO" , "DOM" , "214" , "NA" , "République Dominicaine"                    , "Dominican Republic"                           ],
        "DZ": [ "DZ" , "DZA" , "12"  , "AF" , "Algérie"                                   , "Algeria"                                      ],
        "EC": [ "EC" , "ECU" , "218" , "SA" , "Équateur"                                  , "Ecuador"                                      ],
        "EE": [ "EE" , "EST" , "233" , "EU" , "Estonie"                                   , "Estonia"                                      ],
        "EG": [ "EG" , "EGY" , "818" , "AF" , "Égypte"                                    , "Egypt"                                        ],
        "EH": [ "EH" , "ESH" , "732" , "AF" , "Sahara Occidental"                         , "Western Sahara"                               ],
        "ER": [ "ER" , "ERI" , "232" , "AF" , "Érythrée"                                  , "Eritrea"                                      ],
        "ES": [ "ES" , "ESP" , "724" , "EU" , "Espagne"                                   , "Spain"                                        ],
        "ET": [ "ET" , "ETH" , "231" , "AF" , "Éthiopie"                                  , "Ethiopia"                                     ],
        "FI": [ "FI" , "FIN" , "246" , "EU" , "Finlande"                                  , "Finland"                                      ],
        "FJ": [ "FJ" , "FJI" , "242" , "OC" , "Fidji"                                     , "Fiji"                                         ],
        "FK": [ "FK" , "FLK" , "238" , "SA" , "Îles (malvinas) Falkland"                  , "Falkland Islands"                             ],
        "FM": [ "FM" , "FSM" , "583" , "OC" , "États Fédérés de Micronésie"               , "Federated States of Micronesia"               ],
        "FO": [ "FO" , "FRO" , "234" , "EU" , "Îles Féroé"                                , "Faroe Islands"                                ],
        "FR": [ "FR" , "FRA" , "250" , "EU" , "France"                                    , "France"                                       ],
        "GA": [ "GA" , "GAB" , "266" , "AF" , "Gabon"                                     , "Gabon"                                        ],
        "GB": [ "GB" , "GBR" , "826" , "EU" , "Royaume-Uni"                               , "United Kingdom"                               ],
        "GD": [ "GD" , "GRD" , "308" , "NA" , "Grenade"                                   , "Grenada"                                      ],
        "GE": [ "GE" , "GEO" , "268" , "AS" , "Géorgie"                                   , "Georgia"                                      ],
        "GF": [ "GF" , "GUF" , "254" , "SA" , "Guyane Française"                          , "French Guiana"                                ],
        "GH": [ "GH" , "GHA" , "288" , "AF" , "Ghana"                                     , "Ghana"                                        ],
        "GI": [ "GI" , "GIB" , "292" , "EU" , "Gibraltar"                                 , "Gibraltar"                                    ],
        "GL": [ "GL" , "GRL" , "304" , "NA" , "Groenland"                                 , "Greenland"                                    ],
        "GM": [ "GM" , "GMB" , "270" , "AF" , "Gambie"                                    , "Gambia"                                       ],
        "GN": [ "GN" , "GIN" , "324" , "AF" , "Guinée"                                    , "Guinea"                                       ],
        "GP": [ "GP" , "GLP" , "312" , "NA" , "Guadeloupe"                                , "Guadeloupe"                                   ],
        "GQ": [ "GQ" , "GNQ" , "226" , "AF" , "Guinée Équatoriale"                        , "Equatorial Guinea"                            ],
        "GR": [ "GR" , "GRC" , "300" , "EU" , "Grèce"                                     , "Greece"                                       ],
        "GS": [ "GS" , "SGS" , "239" , "AN" , "Géorgie du Sud et les Îles Sandwich du Sud", "South Georgia and the South Sandwich Islands" ],
        "GT": [ "GT" , "GTM" , "320" , "NA" , "Guatemala"                                 , "Guatemala"                                    ],
        "GU": [ "GU" , "GUM" , "316" , "OC" , "Guam"                                      , "Guam"                                         ],
        "GW": [ "GW" , "GNB" , "624" , "AF" , "Guinée-Bissau"                             , "Guinea-Bissau"                                ],
        "GY": [ "GY" , "GUY" , "328" , "SA" , "Guyana"                                    , "Guyana"                                       ],
        "HK": [ "HK" , "HKG" , "344" , "AS" , "Hong-Kong"                                 , "Hong Kong"                                    ],
        "HM": [ "HM" , "HMD" , "334" , "AN" , "Îles Heard et Mcdonald"                    , "Heard Island and McDonald Islands"            ],
        "HN": [ "HN" , "HND" , "340" , "NA" , "Honduras"                                  , "Honduras"                                     ],
        "HR": [ "HR" , "HRV" , "191" , "EU" , "Croatie"                                   , "Croatia"                                      ],
        "HT": [ "HT" , "HTI" , "332" , "NA" , "Haïti"                                     , "Haiti"                                        ],
        "HU": [ "HU" , "HUN" , "348" , "EU" , "Hongrie"                                   , "Hungary"                                      ],
        "ID": [ "ID" , "IDN" , "360" , "AS" , "Indonésie"                                 , "Indonesia"                                    ],
        "IE": [ "IE" , "IRL" , "372" , "EU" , "Irlande"                                   , "Ireland"                                      ],
        "IL": [ "IL" , "ISR" , "376" , "AS" , "Israël"                                    , "Israel"                                       ],
        "IM": [ "IM" , "IMN" , "833" , "EU" , "Île de Man"                                , "Isle of Man"                                  ],
        "IN": [ "IN" , "IND" , "356" , "AS" , "Inde"                                      , "India"                                        ],
        "IO": [ "IO" , "IOT" , "86"  , "AS" , "Territoire Britannique de l'Océan Indien"  , "British Indian Ocean Territory"               ],
        "IQ": [ "IQ" , "IRQ" , "368" , "AS" , "Iraq"                                      , "Iraq"                                         ],
        "IR": [ "IR" , "IRN" , "364" , "AS" , "République Islamique d'Iran"               , "Islamic Republic of Iran"                     ],
        "IS": [ "IS" , "ISL" , "352" , "EU" , "Islande"                                   , "Iceland"                                      ],
        "IT": [ "IT" , "ITA" , "380" , "EU" , "Italie"                                    , "Italy"                                        ],
        "JM": [ "JM" , "JAM" , "388" , "NA" , "Jamaïque"                                  , "Jamaica"                                      ],
        "JO": [ "JO" , "JOR" , "400" , "AS" , "Jordanie"                                  , "Jordan"                                       ],
        "JP": [ "JP" , "JPN" , "392" , "AS" , "Japon"                                     , "Japan"                                        ],
        "KE": [ "KE" , "KEN" , "404" , "AF" , "Kenya"                                     , "Kenya"                                        ],
        "KG": [ "KG" , "KGZ" , "417" , "AS" , "Kirghizistan"                              , "Kyrgyzstan"                                   ],
        "KH": [ "KH" , "KHM" , "116" , "AS" , "Cambodge"                                  , "Cambodia"                                     ],
        "KI": [ "KI" , "KIR" , "296" , "OC" , "Kiribati"                                  , "Kiribati"                                     ],
        "KM": [ "KM" , "COM" , "174" , "AF" , "Comores"                                   , "Comoros"                                      ],
        "KN": [ "KN" , "KNA" , "659" , "NA" , "Saint-Kitts-et-Nevis"                      , "Saint Kitts and Nevis"                        ],
        "KP": [ "KP" , "PRK" , "408" , "AS" , "République Populaire Démocratique de Corée", "Democratic People's Republic of Korea"        ],
        "KR": [ "KR" , "KOR" , "410" , "AS" , "République de Corée"                       , "Republic of Korea"                            ],
        "KW": [ "KW" , "KWT" , "414" , "AS" , "Koweït"                                    , "Kuwait"                                       ],
        "KY": [ "KY" , "CYM" , "136" , "NA" , "Îles Caïmanes"                             , "Cayman Islands"                               ],
        "KZ": [ "KZ" , "KAZ" , "398" , "AS" , "Kazakhstan"                                , "Kazakhstan"                                   ],
        "LA": [ "LA" , "LAO" , "418" , "AS" , "République Démocratique Populaire Lao"     , "Lao People's Democratic Republic"             ],
        "LB": [ "LB" , "LBN" , "422" , "AS" , "Liban"                                     , "Lebanon"                                      ],
        "LC": [ "LC" , "LCA" , "662" , "NA" , "Sainte-Lucie"                              , "Saint Lucia"                                  ],
        "LI": [ "LI" , "LIE" , "438" , "EU" , "Liechtenstein"                             , "Liechtenstein"                                ],
        "LK": [ "LK" , "LKA" , "144" , "AS" , "Sri Lanka"                                 , "Sri Lanka"                                    ],
        "LR": [ "LR" , "LBR" , "430" , "AF" , "Libéria"                                   , "Liberia"                                      ],
        "LS": [ "LS" , "LSO" , "426" , "AF" , "Lesotho"                                   , "Lesotho"                                      ],
        "LT": [ "LT" , "LTU" , "440" , "EU" , "Lituanie"                                  , "Lithuania"                                    ],
        "LU": [ "LU" , "LUX" , "442" , "EU" , "Luxembourg"                                , "Luxembourg"                                   ],
        "LV": [ "LV" , "LVA" , "428" , "EU" , "Lettonie"                                  , "Latvia"                                       ],
        "LY": [ "LY" , "LBY" , "434" , "AF" , "Jamahiriya Arabe Libyenne"                 , "Libyan Arab Jamahiriya"                       ],
        "MA": [ "MA" , "MAR" , "504" , "AF" , "Maroc"                                     , "Morocco"                                      ],
        "MC": [ "MC" , "MCO" , "492" , "EU" , "Monaco"                                    , "Monaco"                                       ],
        "MD": [ "MD" , "MDA" , "498" , "EU" , "République de Moldova"                     , "Republic of Moldova"                          ],
        "ME": [ "ME" , "MNE" , "499" , "EU" , "Monténégro"                                , "Montenegro, Republic of"                      ],
        "MF": [ "MF" , "MAF" , "663" , "NA" , "Saint Martin"                              , "Saint Martin"                                 ],
        "MG": [ "MG" , "MDG" , "450" , "AF" , "Madagascar"                                , "Madagascar"                                   ],
        "MH": [ "MH" , "MHL" , "584" , "OC" , "Îles Marshall"                             , "Marshall Islands"                             ],
        "MK": [ "MK" , "MKD" , "807" , "EU" , "L'ex-République Yougoslave de Macédoine"   , "The Former Yugoslav Republic of Macedonia"    ],
        "ML": [ "ML" , "MLI" , "466" , "AF" , "Mali"                                      , "Mali"                                         ],
        "MM": [ "MM" , "MMR" , "104" , "AS" , "Myanmar"                                   , "Myanmar"                                      ],
        "MN": [ "MN" , "MNG" , "496" , "AS" , "Mongolie"                                  , "Mongolia"                                     ],
        "MO": [ "MO" , "MAC" , "446" , "AS" , "Macao"                                     , "Macao"                                        ],
        "MP": [ "MP" , "MNP" , "580" , "OC" , "Îles Mariannes du Nord"                    , "Northern Mariana Islands"                     ],
        "MQ": [ "MQ" , "MTQ" , "474" , "NA" , "Martinique"                                , "Martinique"                                   ],
        "MR": [ "MR" , "MRT" , "478" , "AF" , "Mauritanie"                                , "Mauritania"                                   ],
        "MS": [ "MS" , "MSR" , "500" , "NA" , "Montserrat"                                , "Montserrat"                                   ],
        "MT": [ "MT" , "MLT" , "470" , "EU" , "Malte"                                     , "Malta"                                        ],
        "MU": [ "MU" , "MUS" , "480" , "AF" , "Maurice"                                   , "Mauritius"                                    ],
        "MV": [ "MV" , "MDV" , "462" , "AS" , "Maldives"                                  , "Maldives"                                     ],
        "MW": [ "MW" , "MWI" , "454" , "AF" , "Malawi"                                    , "Malawi"                                       ],
        "MX": [ "MX" , "MEX" , "484" , "NA" , "Mexique"                                   , "Mexico"                                       ],
        "MY": [ "MY" , "MYS" , "458" , "AS" , "Malaisie"                                  , "Malaysia"                                     ],
        "MZ": [ "MZ" , "MOZ" , "508" , "AF" , "Mozambique"                                , "Mozambique"                                   ],
        "NA": [ "NA" , "NAM" , "516" , "AF" , "Namibie"                                   , "Namibia"                                      ],
        "NC": [ "NC" , "NCL" , "540" , "OC" , "Nouvelle-Calédonie"                        , "New Caledonia"                                ],
        "NE": [ "NE" , "NER" , "562" , "AF" , "Niger"                                     , "Niger"                                        ],
        "NF": [ "NF" , "NFK" , "574" , "OC" , "Île Norfolk"                               , "Norfolk Island"                               ],
        "NG": [ "NG" , "NGA" , "566" , "AF" , "Nigéria"                                   , "Nigeria"                                      ],
        "NI": [ "NI" , "NIC" , "558" , "NA" , "Nicaragua"                                 , "Nicaragua"                                    ],
        "NL": [ "NL" , "NLD" , "528" , "EU" , "Pays-Bas"                                  , "Netherlands"                                  ],
        "NO": [ "NO" , "NOR" , "578" , "EU" , "Norvège"                                   , "Norway"                                       ],
        "NP": [ "NP" , "NPL" , "524" , "AS" , "Népal"                                     , "Nepal"                                        ],
        "NR": [ "NR" , "NRU" , "520" , "OC" , "Nauru"                                     , "Nauru"                                        ],
        "NU": [ "NU" , "NIU" , "570" , "OC" , "Niué"                                      , "Niue"                                         ],
        "NZ": [ "NZ" , "NZL" , "554" , "OC" , "Nouvelle-Zélande"                          , "New Zealand"                                  ],
        "OM": [ "OM" , "OMN" , "512" , "AS" , "Oman"                                      , "Oman"                                         ],
        "PA": [ "PA" , "PAN" , "591" , "NA" , "Panama"                                    , "Panama"                                       ],
        "PE": [ "PE" , "PER" , "604" , "SA" , "Pérou"                                     , "Peru"                                         ],
        "PF": [ "PF" , "PYF" , "258" , "OC" , "Polynésie Française"                       , "French Polynesia"                             ],
        "PG": [ "PG" , "PNG" , "598" , "OC" , "Papouasie-Nouvelle-Guinée"                 , "Papua New Guinea"                             ],
        "PH": [ "PH" , "PHL" , "608" , "AS" , "Philippines"                               , "Philippines"                                  ],
        "PK": [ "PK" , "PAK" , "586" , "AS" , "Pakistan"                                  , "Pakistan"                                     ],
        "PL": [ "PL" , "POL" , "616" , "EU" , "Pologne"                                   , "Poland"                                       ],
        "PM": [ "PM" , "SPM" , "666" , "NA" , "Saint-Pierre-et-Miquelon"                  , "Saint-Pierre and Miquelon"                    ],
        "PN": [ "PN" , "PCN" , "612" , "OC" , "Pitcairn"                                  , "Pitcairn"                                     ],
        "PR": [ "PR" , "PRI" , "630" , "NA" , "Porto Rico"                                , "Puerto Rico"                                  ],
        "PS": [ "PS" , "PSE" , "275" , "AS" , "Territoire Palestinien Occupé"             , "Occupied Palestinian Territory"               ],
        "PT": [ "PT" , "PRT" , "620" , "EU" , "Portugal"                                  , "Portugal"                                     ],
        "PW": [ "PW" , "PLW" , "585" , "OC" , "Palaos"                                    , "Palau"                                        ],
        "PY": [ "PY" , "PRY" , "600" , "SA" , "Paraguay"                                  , "Paraguay"                                     ],
        "QA": [ "QA" , "QAT" , "634" , "AS" , "Qatar"                                     , "Qatar"                                        ],
        "RE": [ "RE" , "REU" , "638" , "AF" , "Réunion"                                   , "Réunion"                                      ],
        "RO": [ "RO" , "ROU" , "642" , "EU" , "Roumanie"                                  , "Romania"                                      ],
        "RS": [ "RS" , "SRB" , "688" , "EU" , "Serbie"                                    , "Serbia, Republic of"                          ],
        "RU": [ "RU" , "RUS" , "643" , "EU" , "Fédération de Russie"                      , "Russian Federation"                           ],
        "RW": [ "RW" , "RWA" , "646" , "AF" , "Rwanda"                                    , "Rwanda"                                       ],
        "SA": [ "SA" , "SAU" , "682" , "AS" , "Arabie Saoudite"                           , "Saudi Arabia"                                 ],
        "SB": [ "SB" , "SLB" , "90"  , "OC" , "Îles Salomon"                              , "Solomon Islands"                              ],
        "SC": [ "SC" , "SYC" , "690" , "AF" , "Seychelles"                                , "Seychelles"                                   ],
        "SD": [ "SD" , "SDN" , "736" , "AF" , "Soudan"                                    , "Sudan"                                        ],
        "SE": [ "SE" , "SWE" , "752" , "EU" , "Suède"                                     , "Sweden"                                       ],
        "SG": [ "SG" , "SGP" , "702" , "AS" , "Singapour"                                 , "Singapore"                                    ],
        "SH": [ "SH" , "SHN" , "654" , "AF" , "Sainte-Hélène"                             , "Saint Helena"                                 ],
        "SI": [ "SI" , "SVN" , "705" , "EU" , "Slovénie"                                  , "Slovenia"                                     ],
        "SJ": [ "SJ" , "SJM" , "744" , "EU" , "Svalbard etÎle Jan Mayen"                  , "Svalbard and Jan Mayen"                       ],
        "SK": [ "SK" , "SVK" , "703" , "EU" , "Slovaquie"                                 , "Slovakia"                                     ],
        "SL": [ "SL" , "SLE" , "694" , "AF" , "Sierra Leone"                              , "Sierra Leone"                                 ],
        "SM": [ "SM" , "SMR" , "674" , "EU" , "Saint-Marin"                               , "San Marino"                                   ],
        "SN": [ "SN" , "SEN" , "686" , "AF" , "Sénégal"                                   , "Senegal"                                      ],
        "SO": [ "SO" , "SOM" , "706" , "AF" , "Somalie"                                   , "Somalia"                                      ],
        "SR": [ "SR" , "SUR" , "740" , "SA" , "Suriname"                                  , "Suriname"                                     ],
        "ST": [ "ST" , "STP" , "678" , "AF" , "Sao Tomé-et-Principe"                      , "Sao Tome and Principe"                        ],
        "SV": [ "SV" , "SLV" , "222" , "NA" , "El Salvador"                               , "El Salvador"                                  ],
        "SY": [ "SY" , "SYR" , "760" , "AS" , "République Arabe Syrienne"                 , "Syrian Arab Republic"                         ],
        "SZ": [ "SZ" , "SWZ" , "748" , "AF" , "Swaziland"                                 , "Swaziland"                                    ],
        "TC": [ "TC" , "TCA" , "796" , "NA" , "Îles Turks et Caïques"                     , "Turks and Caicos Islands"                     ],
        "TD": [ "TD" , "TCD" , "148" , "AF" , "Tchad"                                     , "Chad"                                         ],
        "TF": [ "TF" , "ATF" , "260" , "AN" , "Terres Australes Françaises"               , "French Southern Territories"                  ],
        "TG": [ "TG" , "TGO" , "768" , "AF" , "Togo"                                      , "Togo"                                         ],
        "TH": [ "TH" , "THA" , "764" , "AS" , "Thaïlande"                                 , "Thailand"                                     ],
        "TJ": [ "TJ" , "TJK" , "762" , "AS" , "Tadjikistan"                               , "Tajikistan"                                   ],
        "TK": [ "TK" , "TKL" , "772" , "OC" , "Tokelau"                                   , "Tokelau"                                      ],
        "TL": [ "TL" , "TLS" , "626" , "AS" , "Timor-Leste"                               , "Timor-Leste"                                  ],
        "TM": [ "TM" , "TKM" , "795" , "AS" , "Turkménistan"                              , "Turkmenistan"                                 ],
        "TN": [ "TN" , "TUN" , "788" , "AF" , "Tunisie"                                   , "Tunisia"                                      ],
        "TO": [ "TO" , "TON" , "776" , "OC" , "Tonga"                                     , "Tonga"                                        ],
        "TR": [ "TR" , "TUR" , "792" , "EU" , "Turquie"                                   , "Turkey"                                       ],
        "TT": [ "TT" , "TTO" , "780" , "NA" , "Trinité-et-Tobago"                         , "Trinidad and Tobago"                          ],
        "TV": [ "TV" , "TUV" , "798" , "OC" , "Tuvalu"                                    , "Tuvalu"                                       ],
        "TW": [ "TW" , "TWN" , "158" , "AS" , "Taïwan"                                    , "Taiwan"                                       ],
        "TZ": [ "TZ" , "TZA" , "834" , "AF" , "République-Unie de Tanzanie"               , "United Republic Of Tanzania"                  ],
        "UA": [ "UA" , "UKR" , "804" , "EU" , "Ukraine"                                   , "Ukraine"                                      ],
        "UG": [ "UG" , "UGA" , "800" , "AF" , "Ouganda"                                   , "Uganda"                                       ],
        "UM": [ "UM" , "UMI" , "581" , "OC" , "Îles Mineures Éloignées des États-Unis"    , "United States Minor Outlying Islands"         ],
        "US": [ "US" , "USA" , "840" , "NA" , "États-Unis"                                , "United States"                                ],
        "UY": [ "UY" , "URY" , "858" , "SA" , "Uruguay"                                   , "Uruguay"                                      ],
        "UZ": [ "UZ" , "UZB" , "860" , "AS" , "Ouzbékistan"                               , "Uzbekistan"                                   ],
        "VA": [ "VA" , "VAT" , "336" , "EU" , "Saint-Siège (état de la Cité du Vatican)"  , "Vatican City State"                           ],
        "VC": [ "VC" , "VCT" , "670" , "NA" , "Saint-Vincent-et-les Grenadines"           , "Saint Vincent and the Grenadines"             ],
        "VE": [ "VE" , "VEN" , "862" , "SA" , "Venezuela"                                 , "Venezuela"                                    ],
        "VG": [ "VG" , "VGB" , "92"  , "NA" , "Îles Vierges Britanniques"                 , "British Virgin Islands"                       ],
        "VI": [ "VI" , "VIR" , "850" , "NA" , "Îles Vierges des États-Unis"               , "U.S. Virgin Islands"                          ],
        "VN": [ "VN" , "VNM" , "704" , "AS" , "Viet Nam"                                  , "Vietnam"                                      ],
        "VU": [ "VU" , "VUT" , "548" , "OC" , "Vanuatu"                                   , "Vanuatu"                                      ],
        "WF": [ "WF" , "WLF" , "876" , "OC" , "Wallis et Futuna"                          , "Wallis and Futuna"                            ],
        "WS": [ "WS" , "WSM" , "882" , "OC" , "Samoa"                                     , "Samoa"                                        ],
        "YE": [ "YE" , "YEM" , "887" , "AS" , "Yémen"                                     , "Yemen"                                        ],
        "YT": [ "YT" , "MYT" , "175" , "AF" , "Mayotte"                                   , "Mayotte"                                      ],
        "ZA": [ "ZA" , "ZAF" , "710" , "AF" , "Afrique du Sud"                            , "South Africa"                                 ],
        "ZM": [ "ZM" , "ZMB" , "894" , "AF" , "Zambie"                                    , "Zambia"                                       ],
        "ZW": [ "ZW" , "ZWE" , "716" , "AF" , "Zimbabwe"                                  , "Zimbabwe"                                     ]
    ]
}